# Generated by Django 5.2.9 on 2026-03-17 22:00

import plugininstances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0004_plugininstance_deletion_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plugininstance',
            name='summary',
            field=models.JSONField(blank=True, default=plugininstances.models.get_default_job_status_summary),
        ),
    ]
