# Generated by Django 5.2.9 on 2026-03-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugininstances', '0005_alter_plugininstance_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugininstance',
            name='remote_cleanup_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plugininstance',
            name='remote_cleanup_status',
            field=models.CharField(choices=[('notStarted', 'Not started'), ('deletingData', 'Deleting remote data'), ('deletingContainers', 'Deleting remote containers'), ('complete', 'Cleanup complete'), ('failed', 'Cleanup failed')], default='notStarted', max_length=30),
        ),
    ]
